server:
    port: 8081
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/manage_bx?serverTimezone=UTC
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
    configguration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        global-config:
        db-config:
            id-type: auto
            logic-delete-field: delete
            logic-delete-value: 1
            logic-not-delete-value: 0

# mybatis≈‰÷√
mybatis.mapper-locations: classpath:mapper/*.xml
mybatis.type-aliases-package: com.example.manage.app.pojo.entity